# Generated by Django 4.1.7 on 2023-03-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
